export const STRINGS = Object.freeze({
  subtitle: '{欧州|おうしゅう}5{大|だい}リーグ{大図鑑|だいずかん}',
  home: 'ホーム',
  credits: 'クレジット',
  loading: '{読|よ}み{込|こ}み{中|ちゅう}…',
  pageNotFound: 'ページが{見|み}つかりません',
  dataError: 'データを{読|よ}み{込|こ}めませんでした',
  retry: 'もう{一度|いちど}{読|よ}み{込|こ}む',
  champion: '{優勝|ゆうしょう}',
  topScorer: '{得点王|とくてんおう}',
  titleCount: '{優勝回数|ゆうしょうかいすう}',
  japanFeature: '{日本人選手|にほんじんせんしゅ}',
  meikan: '{選手名鑑|せんしゅめいかん}',
  rankings: '{ランキング|らんきんぐ}',
  search: '{検索|けんさく}',
  searchLabel: '{選手|せんしゅ}や{クラブ|くらぶ}をさがす',
  noSearchResults: '{見|み}つかりませんでした',
  noRecord: '{記録|きろく}なし',
  noGoalRecord: '{記録|きろく}のある{試合|しあい}だけ',
});
